разметка страниц
htmlacademy-htmlcss/2473597-sedona-1 pull request #2
Opened 2024-04-17 15:30 UTC by xylianas

в отпуске забыла про курс, прошу прощения, что поздно гружу :(

2024-04-17 15:48 UTC, Kartaviy-arteom requested changes

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +                <fieldset class="catalog-filter-group">
форматирование документа

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +                    </li>
связать в группу

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +                      <label class="catalog-filter-label" for="min-price"></label>
добавить описание

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +                        <button class="range-toggle toggle-min">
type=button

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +              </a>
список

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +              <span class="visually-hidden">Подписаться</span>
visually-hidden не нужен

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +          <p class="about-text">Сделано в <a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a></p>
логотип - контентна картинка

2024-04-17 15:48 UTC, Kartaviy-arteom commented on catalogue.html
> +          <h1>+7 (812) 812-12-12</h1>
ссылка

2024-04-17 15:48 UTC, Kartaviy-arteom commented on index.html
> +        <img class="logo" src="" alt="Логотип Седоны">
поместить в секцию

2024-04-17 15:48 UTC, Kartaviy-arteom commented on index.html
> +        <section class="services">
объединить в одну секцию

2024-04-17 15:48 UTC, Kartaviy-arteom commented on index.html
> +              <span class="visually-hidden">Подписаться</span>
vissually-hidden не нужен

2024-04-20 15:20 UTC, xylianas commented on catalogue.html
> +                <fieldset class="catalog-filter-group">
здесь про лишний абзац или что-то ещё?

2024-04-20 16:17 UTC, xylianas commented on catalogue.html
> +          <p class="about-text">Сделано в <a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a></p>
можете подробнее объяснить, что нужно исправить, пожалуйста

2024-04-20 16:18 UTC, xylianas commented on catalogue.html
> +          <h1>+7 (812) 812-12-12</h1>
и тут тоже, какой ссылки не хватает

2024-05-08 13:25 UTC, closed without merging